//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 11 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: BunnyScene
      ///
      /// Key: BunnyScene
      ///
      /// Locales: en
      var bunnyScene: RswiftResources.StringResource { .init(key: "BunnyScene", tableName: "Localizable", source: source, developmentValue: "BunnyScene", comment: nil) }

      /// en translation: goal
      ///
      /// Key: Goal
      ///
      /// Locales: en
      var goal: RswiftResources.StringResource { .init(key: "Goal", tableName: "Localizable", source: source, developmentValue: "goal", comment: nil) }

      /// en translation: Hero
      ///
      /// Key: Hero
      ///
      /// Locales: en
      var hero: RswiftResources.StringResource { .init(key: "Hero", tableName: "Localizable", source: source, developmentValue: "Hero", comment: nil) }

      /// en translation: obstacle
      ///
      /// Key: Obstacle
      ///
      /// Locales: en
      var obstacle: RswiftResources.StringResource { .init(key: "Obstacle", tableName: "Localizable", source: source, developmentValue: "obstacle", comment: nil) }

      /// en translation: obstacleLayer
      ///
      /// Key: ObstacleLayer
      ///
      /// Locales: en
      var obstacleLayer: RswiftResources.StringResource { .init(key: "ObstacleLayer", tableName: "Localizable", source: source, developmentValue: "obstacleLayer", comment: nil) }

      /// en translation: previousScore
      ///
      /// Key: PreviousScore
      ///
      /// Locales: en
      var previousScore: RswiftResources.StringResource { .init(key: "PreviousScore", tableName: "Localizable", source: source, developmentValue: "previousScore", comment: nil) }

      /// en translation: resetButton
      ///
      /// Key: ResetButton
      ///
      /// Locales: en
      var resetButton: RswiftResources.StringResource { .init(key: "ResetButton", tableName: "Localizable", source: source, developmentValue: "resetButton", comment: nil) }

      /// en translation: scoreLabel
      ///
      /// Key: ScoreLabel
      ///
      /// Locales: en
      var scoreLabel: RswiftResources.StringResource { .init(key: "ScoreLabel", tableName: "Localizable", source: source, developmentValue: "scoreLabel", comment: nil) }

      /// en translation: scrollCloudLayer
      ///
      /// Key: ScrollCloudLayer
      ///
      /// Locales: en
      var scrollCloudLayer: RswiftResources.StringResource { .init(key: "ScrollCloudLayer", tableName: "Localizable", source: source, developmentValue: "scrollCloudLayer", comment: nil) }

      /// en translation: scrollGroundlLayer
      ///
      /// Key: ScrollGroundlLayer
      ///
      /// Locales: en
      var scrollGroundlLayer: RswiftResources.StringResource { .init(key: "ScrollGroundlLayer", tableName: "Localizable", source: source, developmentValue: "scrollGroundlLayer", comment: nil) }

      /// en translation: Shake
      ///
      /// Key: Shake
      ///
      /// Locales: en
      var shake: RswiftResources.StringResource { .init(key: "Shake", tableName: "Localizable", source: source, developmentValue: "Shake", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 10 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `background`.
    var background: RswiftResources.ImageResource { .init(name: "background", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bg_crystals`.
    var bg_crystals: RswiftResources.ImageResource { .init(name: "bg_crystals", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bunny1`.
    var bunny1: RswiftResources.ImageResource { .init(name: "bunny1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bunny2`.
    var bunny2: RswiftResources.ImageResource { .init(name: "bunny2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `carrot_bottom`.
    var carrot_bottom: RswiftResources.ImageResource { .init(name: "carrot_bottom", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `carrot_top`.
    var carrot_top: RswiftResources.ImageResource { .init(name: "carrot_top", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `clouds`.
    var clouds: RswiftResources.ImageResource { .init(name: "clouds", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ground`.
    var ground: RswiftResources.ImageResource { .init(name: "ground", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `play_button`.
    var play_button: RswiftResources.ImageResource { .init(name: "play_button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `restart_button`.
    var restart_button: RswiftResources.ImageResource { .init(name: "restart_button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.file` struct is generated, and contains static references to 4 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Actions.sks`.
    var actionsSks: RswiftResources.FileResource { .init(name: "Actions", pathExtension: "sks", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `BunnyScene.sks`.
    var bunnySceneSks: RswiftResources.FileResource { .init(name: "BunnyScene", pathExtension: "sks", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Hero.sks`.
    var heroSks: RswiftResources.FileResource { .init(name: "Hero", pathExtension: "sks", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `ObstaclesScene.sks`.
    var obstaclesSceneSks: RswiftResources.FileResource { .init(name: "ObstaclesScene", pathExtension: "sks", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }
    var scoreScreenTemplate: scoreScreenTemplate { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func scoreScreenTemplate(bundle: Foundation.Bundle) -> scoreScreenTemplate {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
      try self.main.validate()
      try self.scoreScreenTemplate.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = GameViewController

      let bundle: Foundation.Bundle

      let name = "Main"

      var gameViewController: RswiftResources.StoryboardViewControllerIdentifier<GameViewController> { .init(identifier: "GameViewController", storyboard: name, bundle: bundle) }

      func validate() throws {
        if gameViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'gameViewController' could not be loaded from storyboard 'Main' as 'GameViewController'.") }
      }
    }

    /// Storyboard `ScoreScreenTemplate`.
    struct scoreScreenTemplate: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UINavigationController

      let bundle: Foundation.Bundle

      let name = "ScoreScreenTemplate"

      var scoreVC: RswiftResources.StoryboardViewControllerIdentifier<ScoreScreenViewController> { .init(identifier: "scoreVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "xmark") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'xmark' is used in storyboard 'ScoreScreenTemplate', but couldn't be loaded.") } }
        if scoreVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'scoreVC' could not be loaded from storyboard 'ScoreScreenTemplate' as 'ScoreScreenViewController'.") }
      }
    }
  }
}